### PR TITLE
swift 3 support, fix Rx dependence issue, minor project changes to speed up tests

### PR DESCRIPTION
**Pull request by shams-ahmed**
- [ ] git tag 
- [ ] push pod to trunk
- [ ]  🎉

### CODE REVIEW

**Comment by chow-land** [comment]
@ashfurrow any way you could get this merged in? A Swift 3 compatible version would come in very handy right now :)

**Comment by ashfurrow** [comment]
Hi, yes! Definitely. Will merge + release today. Sorry for the wait!

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Comment by ashfurrow** [comment]
okay, this has been released as 1.0.0, thanks again!

**Pull request merged**
