### PR TITLE
[WIP] Release v3.0.0

### PR DESCRIPTION
**Pull request by mosamer**
- This PR aims to implement a major release v3.0.0, which extends `RxNimble` to support `RxTest` and add support to other `RxBlocking` operators as well.
- A new introduction is the concept of `Expectation` transforms, which moves the transforming utilities ,e.g. `toBlocking().first` from matcher to expectation. This will allow using the full set of `Nimble` matchers instead of having to re-implement them. Example:
```
it("can use different matchers") {
   let subject = ReplaySubject<String>.createUnbounded()
   subject.onNext("")

   expect(subject).first == ""
   expect(subject).first.to(beEmpty())
}
```

### Scope
- [ ] Update `RxBlocking` extensions
   - [x] Migrate to use `Expectation` transforms
   - [x] Drop old matchers
   - [ ] Add support to other RxBlocking operators
      - [ ] `last`
      - [ ] `timeline`
      - [ ] `single`
- [ ] Add `RxTest` extensions
   - [ ] Support `RxTest.TestableObserver` expectations
   - [ ] Add custom Nimble matchers for timeline and recorded events
- [ ] Update pod specs
   - [ ] Pump up library version to 3.0.0
   - [ ] Update `Nimble` version to 7.0.0
   - [ ] Add subspecs to Blocking/Tests
- [ ] Update README file
- [ ] Update demo project
- [ ] Update CHANGELOG file

### CODE REVIEW

**Comment by vhbit** [comment]
> This will allow using the full set of Nimble matchers instead of having to re-implement them. 

That sounds great! Do you plan to continue on this?

**Comment by mosamer** [comment]
@vhbit yes, sure. It's such a major change (almost a complete re-write) so was looking for some discussion before moving on with it :)

**Comment by freak4pc** [comment]
Hey @mosamer, Currently closing this PR as 
1. It's stale (4 months) 
2. A 4.0.0 based on RxSwift 4 has been released

If you want to pursue your original plan to use the original Nimble matchers, please either rebase on top of the current master or start from the 4.0.0 version and make a new PR.

Thanks and really appreciate your work ! 

Shai

**Comment by mosamer** [comment]
Hi @freak4pc I rebased my branch and opened a new PR ([here](https://github.com/RxSwiftCommunity/RxNimble/pull/28)). will discuss the versioning and any further details on the new PR.

**Pull request closed without merging**
