### PR TITLE
Allow using all Nimble matchers

### PR DESCRIPTION
**Pull request by mosamer**
This PR introduces the concept of `Expectation` transforms, which moves the transforming utilities ,e.g. `toBlocking().first` from matcher to expectation. This will allow using the full set of `Nimble` matchers instead of having to re-implement them. Example:
```
it("can use different matchers") {
   let subject = ReplaySubject<String>.createUnbounded()
   subject.onNext("")

   expect(subject).first == ""
   expect(subject).first.to(beEmpty())
}
```

### Scope
- [x] Update `RxBlocking` extensions
   - [x] Migrate to use `Expectation` transforms
   - [x] Deprecate old matchers
   - [x] Add support to other RxBlocking operators
      - [x] `first`
      - [x] `last`
      - [x] `array`
- [x] Update pod specs
- [x] Update README file
- [x] Update demo project
- [x] Update CHANGELOG file

### CODE REVIEW

**Comment by mosamer** [comment]
As this PR will allow using Nimble built-in matchers, it closes #23 & #22

**Comment by mosamer** [comment]
As v4.0.0 is just released, matcher functions are deprecated -instead of being dropped- to avoid breaking changes. I hence suggest this PR to update version to `4.1.0`.

**Comment by freak4pc** [comment]
Hey @mosamer. This looks great overall. 
I'll want to take a deeper look into it but it would have to wait for tomorrow or the next day :)

**Comment by freak4pc** [comment]
@ashfurrow If you'll have a few minutes would be great to get your feedback as well here since you're knowledgable with Nimble matchers more than most of us :)

**Review by ashfurrow — APPROVED** [review]
@mosamer Good morning! This is a very impressive pull request – very thorough, too! Thank you for taking the time to share these improvements with the rest of the iOS community.

This looks like a fantastic addition to the library, I'm very happy to merge.

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Pull request merged**
