### PR TITLE
Support Carthage

### PR DESCRIPTION
**Pull request by toshi0383**
Added `CarthageSupport.xcodeproj` like [NSObject-Rx](https://github.com/RxSwiftCommunity/NSObject-Rx).

### CODE REVIEW

**Comment by toshi0383** [comment]
It turns out that `CarthageSupport.xcodeproj` might not be a good idea.. I will fix it.
carthage-support-xcodeproj-is-not-a-good-idea

**Comment by toshi0383** [comment]
I think this is ready to go.👌

**Comment by lamson-dev** [comment]
Can someone take a look at this PR and have it merge in, please? I do think this is a great addition to the project.

**Comment by toshi0383** [comment]
I wonder if it still builds on CI.🤔
I close and reopen to rerun the CI.

**Comment by toshi0383** [comment]
Oh it has conflicts anyways.🙃
I don't have time to work on this, so can someone take over this?
Closing for now.

**Pull request closed without merging**
