### PR TITLE
Update to Nimble 9

### PR DESCRIPTION
**Pull request by lordzsolt**
- Bump to version 5.0.0
- Bump to require Nimble 9.0.0
- Fix breaking changes

### CODE REVIEW

**Review by ashfurrow — APPROVED** [review]
Changes look good! Let me know if I can help with CI.

**Comment by lordzsolt** [comment]
> Let me know if I can help with CI.

@ashfurrow Not exactly sure what you mean 😅 

Is there anything else I should do, besides making sure the CI passed?

**Comment by ashfurrow** [comment]
Yes, that's all! Looks like it's working now 😅

**Review by ashfurrow — APPROVED** [review]

**Comment by ashfurrow** [comment]
Ahhh, I'll fix that bot one second...

**Comment by ashfurrow** [comment]
Okay! I fixed the auto-invitation bot here: https://github.com/RxSwiftCommunity/peril/commit/0643b8a0402a73aa7c31262e40b354bbedaebf77

Next, I'll work on releasing this PR 🎉

**Comment by lordzsolt** [comment]
> Okay! I fixed the auto-invitation bot here: [RxSwiftCommunity/peril@0643b8a](https://github.com/RxSwiftCommunity/peril/commit/0643b8a0402a73aa7c31262e40b354bbedaebf77)
> 
> Next, I'll work on releasing this PR 🎉

Perfect 😄 

And thank you for the invitation 🤗

**Comment by ashfurrow** [comment]
I'm still working on it 😅 I've pushed the `5.0.0` branch but it's failing to validate because I think my Xcode is outdated. I'm installing the latest now.

**Comment by ashfurrow** [comment]
Okay that should do it! Note that I had to increase the minimum iOS deployment target to iOS 9.0 (which matches RxSwift). Thanks again!

**Pull request merged**
