### PR TITLE
Updated to be compatible with Nimble 6.1 & newer Swift

### PR DESCRIPTION
**Pull request by vhbit**
This is continuation of work started in #14. I've fixed all the warnings and provided a workaround for building errors through introducing a new `==` operator (more details here: https://github.com/RxSwiftCommunity/RxNimble/commit/59bb147c7a4fff650a97d932e741cee3ca1040ad). As API has a breaking change I've also bumped major version.

### CODE REVIEW

**Comment by vhbit** [comment]
cc @ashfurrow

**Review by ashfurrow — APPROVED** [review]
Looks fantastic, thanks!

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Comment by ashfurrow** [comment]
This has been pushed to CocoaPods trunk, thanks again 🙇

**Comment by RafaelPlantard** [comment]
@vhbit awesome, congrats!

**Review by RafaelPlantard — COMMENTED** [review]
👍

**Pull request merged**
