### PR TITLE
Add support for Swift 4/RxSwift 4/RxBlocking 4

### PR DESCRIPTION
**Pull request by oronbz**

### CODE REVIEW

**Review by freak4pc — CHANGES_REQUESTED** [review]
Looks good. You just forgot a version bump on the Podsec ;-) @oronbz

**Comment by oronbz** [comment]
I saw @ashfurrow doing it on separate commits, but no problem

**Comment by freak4pc** [comment]
Well since this change would break the old version (e.g. Swift 3/3.2 users), it must have a version bump as well usually. 

CI looks green! Just get the new podspec in and we can merge. Thanks dude !

**Review by freak4pc — APPROVED** [review]

**Comment by freak4pc** [comment]
Hey @ashfurrow , Mind pushing a new Podspec for 4.0 when you have a few spare minutes? :)

**Comment by ashfurrow** [comment]
Certainly, I'll do so now.

**Comment by ashfurrow** [comment]
all done 👍

**Comment by freak4pc** [comment]
Thanks a bunch 🙏🙏🙏

**Comment by oronbz** [comment]
Thanks @ashfurrow !

**Pull request merged**
