### PR TITLE
Fix issue #9: support carthage

### PR DESCRIPTION
**Pull request by mingchen**
This pull request by add RxNimble workspace and shared scheme to support carthage.

### CODE REVIEW

**Comment by oronbz** [comment]
@RxSwiftCommunity/contributors I'm not familiar with carthage support can anyone give input on this?

**Comment by freak4pc** [comment]
@mingchen This looks OK to me, but CI is failing. Could you fix this before I fully review ?

**Comment by oronbz** [comment]
@mingchen rebase it after https://github.com/RxSwiftCommunity/RxNimble/pull/27 is merged and you should be fine.

**Comment by freak4pc** [comment]
Hey @mingchen, Can you rebase on master and push this back ? Thanks !

**Comment by freak4pc** [comment]
Hey @mingchen , No rush but any plans to get back around to fix this PR so we can resolve Carthage support? Thanks !

**Comment by gobetti** [comment]
@freak4pc just in case, I have written a separate branch adding support to Carthage on top of master, TBH I hadn't seen this PR open before but let me know if you'd rather fix this or have a new PR. Thanks!

**Comment by freak4pc** [comment]
Hey @gobetti - Please do :) If you have a separate PR that resolves this, please push it up and I'll review. Thanks !

**Comment by gobetti** [comment]
Hi @freak4pc I'm sorry it took longer than expected, I had trouble fine-tuning my existent branch after the RxTest support got merged. It's open now (#36). Thanks!

**Comment by freak4pc** [comment]
Closing this in favour of #36.

**Pull request closed without merging**
