### PR TITLE
Swift 5

### PR DESCRIPTION
**Pull request by t-unit**
Update to 
* Xcode 10.2
* RxSwift 5
* Swift 5
* latest versions of Quick and Nimble

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hmm, I took a quick look and I'm not sure what to make of the CI failures. I know that #42 changed the dependencies to be explicit. I don't see where RxAtomic is even used in this project, so removing it should be fine 👍 The Travis CI setup is more complicated than I remember, but let me know if I can help!

**Comment by t-unit** [comment]
Seems RxAtomic really was the problem. As far as I can tell it got removed from RxSwift with version 5. Just not sure why the build/tests did not fail locally…

**Comment by ashfurrow** [comment]
Seems to be passing now! I'm going to merge – should we cut a new release with these changes?

**Comment by t-unit** [comment]
Thx for merging. A new release would be a highly appreciated!

**Comment by ashfurrow** [comment]
Okay! That's been released as 4.5.0. Thanks again!

**Pull request merged**
