### PR TITLE
Change ObservableType to ObservableConvertibleType

### LINKED ISSUE #32: Expectation not supporting all traits
I personally ran into a problem where Single was not supported. Single is widely used for HTTP requests as we expect just a single value/error, not a stream of multiple events.

Currently, expectation confronts to `T : ObservableType`, if it would be switched to `T: ObservableConvertibleType`, it would support all observables that have `toBlocking` support.

### PR DESCRIPTION
**Pull request by M0rtyMerr**
Resolve https://github.com/RxSwiftCommunity/RxNimble/issues/32

### CODE REVIEW

**Review by mosamer — APPROVED** [review]
LGTM

**Review by freak4pc — COMMENTED** [review]
Looks good. Can you add a CHANGELOG entry ?

**Review by gobetti — APPROVED** [review]

**Comment by M0rtyMerr** [comment]
Hey @freak4pc can I merge this one?

**Comment by freak4pc** [comment]
Hey, no need to mention and ask for review at the same time :) thanks for understanding.

**Review by freak4pc — APPROVED** [review]

**Comment by freak4pc** [comment]
PS you should usually not merge your own PR, one of the contributors is better off doing this to avoid any of the reviewers missing something.

**Comment by M0rtyMerr** [comment]
Sure, sorry 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
