### PR TITLE
Update to Nimble 6.1

### PR DESCRIPTION
**Pull request by RafaelPlantard**
To solve https://github.com/RxSwiftCommunity/RxNimble/issues/13

### CODE REVIEW

**Comment by ashfurrow** [comment]
Cool, this slipped past me sorry for the delay! I've restarted CI 🤞 Looks like a CocoaPods specs repo cache issue, should be fixed now.

**Comment by freak4pc** [comment]
Closed and reopened for travis to restart, let's see if this helps.

**Comment by freak4pc** [comment]
I think we'll need to fix the Podfile.lock file as there seems to be some conflict.

**Comment by ashfurrow** [comment]
Hmm, looks like Travis' CocoaPods Specs repo is out of date. Can you add a `pod repo update` below line 6? https://github.com/RxSwiftCommunity/RxNimble/blob/baa116ef131959d9e6ee7316ca3c0f60243af0d8/.travis.yml#L6

**Comment by freak4pc** [comment]
@RafaelPlantard , Let us know if you need any help with this. Thanks for your assistance!

**Comment by RafaelPlantard** [comment]
I will update right now!

**Comment by freak4pc** [comment]
I'm actually seeing some issues on Swift 3.1 and Xcode 8.3.2 
Perhaps the comparator method signature isn't correct to that case? 

image

**Comment by RafaelPlantard** [comment]
@freak4pc this issue is occurring also into Unit Tests of `RxNimble`. Even updating for:
```
  - Nimble (6.1.0)
  - Quick (1.1.0)
  - RxBlocking (3.4.0):
    - RxSwift (~> 3.4)
  - RxNimble (1.0.1):
    - Nimble (~> 6.0)
    - RxBlocking (~> 3.0)
    - RxSwift (~> 3.0)
  - RxSwift (3.4.0)
```

**Comment by freak4pc** [comment]
This isn't a Nimble version issue, This is a Swift/Comparator issue. 

Explicitly defining a String-type comparator catches for some reason:
```swift
public func ==<O: ObservableType>(lhs: Expectation<O>, rhs: String) where O.E == String {
    lhs.to(equalFirst(expectedValue: rhs))
}
```

But replacing `String` with a Generic conforming to Equatable (which is the current implementation) doesn't catch that term, for some reason. 
```swift
public func ==<T: Equatable, O: ObservableType>(lhs: Expectation<O>, rhs: T) where O.E == T {
    lhs.to(equalFirst(expectedValue: rhs))
}
```

I'd love the thoughts of anyone of the @RxSwiftCommunity/contributors if anyone has a second to share thoughts here.

**Comment by vhbit** [comment]
@RafaelPlantard closing as #17 based on this has landed.

**Pull request closed without merging**
